#pragma once

#include "ref/addrdec.hpp"
#include "ref/cache_access_logger_types.hpp"
#include "ref/cache_config.hpp"
#include "ref/data_cache.hpp"
#include "ref/dim3.hpp"
#include "ref/function_info.hpp"
#include "ref/gpgpu_context.hpp"
#include "ref/gpgpu_sim.hpp"
#include "ref/hal.hpp"
#include "ref/instr.hpp"
#include "ref/l1_cache.hpp"
#include "ref/l2_cache.hpp"
#include "ref/mem_fetch.hpp"
#include "ref/memory_config.hpp"
#include "ref/operand_info.hpp"
#include "ref/operand_type.hpp"
#include "ref/ptx_cta_info.hpp"
#include "ref/ptx_instruction.hpp"
#include "ref/ptx_reg.hpp"
#include "ref/ptx_thread_info.hpp"
#include "ref/symbol_table.hpp"
#include "ref/tag_array.hpp"
#include "ref/warp_instr.hpp"

#include "tests/parse_cache_config.hpp"
