#pragma once

enum set_index_function {
  LINEAR_SET_FUNCTION = 0,
  BITWISE_XORING_FUNCTION,
  HASH_IPOLY_FUNCTION,
  FERMI_HASH_SET_FUNCTION,
  CUSTOM_SET_FUNCTION
};

static const char* set_index_function_str[] = {
    "LINEAR_SET_FUNCTION", "BITWISE_XORING_FUNCTION", "HASH_IPOLY_FUNCTION",
    "FERMI_HASH_SET_FUNCTION", "CUSTOM_SET_FUNCTION"};
